name: laminitis
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - ipywidgets
  - numpy<2
  - dask-labextension  
  - dask
  - dask-image  
  - imageio
  - zarr
  - numcodecs  
  - pandas
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - openpyxl  
  - tabulate
  - skan
  - napari
  - pip
  - pip:
    - flake8
    - pycodestyle_magic
