name: vetsuisse
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - pandas
  - dask
  - dask-image  
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - openpyxl  
  - tabulate
